# -*- coding: utf-8 -*-
# Generated by Django 1.11.5 on 2017-10-04 04:13
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Children',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('FirstName', models.CharField(max_length=40)),
                ('LastName', models.CharField(max_length=40)),
                ('FullName', models.CharField(blank=True, max_length=81, null=True)),
                ('Birthday', models.DateField()),
                ('RAMQ', models.CharField(blank=True, max_length=14, null=True)),
                ('RAMQ_Expiration', models.DateField(blank=True, null=True)),
            ],
        ),
        migrations.CreateModel(
            name='Classe',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('Name', models.CharField(max_length=255)),
            ],
        ),
        migrations.CreateModel(
            name='Educator',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('FirstName', models.CharField(max_length=40)),
                ('LastName', models.CharField(max_length=40)),
                ('Email', models.EmailField(max_length=254)),
                ('Phone', models.CharField(max_length=15)),
                ('Phone_emergency', models.CharField(max_length=15)),
            ],
        ),
        migrations.CreateModel(
            name='Parent',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('FirstName', models.CharField(max_length=40)),
                ('LastName', models.CharField(max_length=40)),
                ('Email', models.EmailField(max_length=254)),
                ('Phone', models.CharField(max_length=15)),
                ('Phone_emergency', models.CharField(max_length=15)),
                ('SIN', models.CharField(max_length=11)),
            ],
        ),
        migrations.AddField(
            model_name='classe',
            name='Educators',
            field=models.ManyToManyField(to='garderie.Educator'),
        ),
        migrations.AddField(
            model_name='children',
            name='Parents',
            field=models.ManyToManyField(to='garderie.Parent'),
        ),
    ]
