# -*- coding: utf-8 -*-
# Generated by Django 1.11.5 on 2017-10-02 02:12
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('garderie', '0002_auto_20171002_0211'),
    ]

    operations = [
        migrations.AlterField(
            model_name='classe',
            name='Classe_ID',
            field=models.AutoField(primary_key=True, serialize=False),
        ),
        migrations.AlterField(
            model_name='educator',
            name='Educator_ID',
            field=models.AutoField(primary_key=True, serialize=False),
        ),
        migrations.AlterField(
            model_name='parent',
            name='Parent_ID',
            field=models.AutoField(primary_key=True, serialize=False),
        ),
    ]
