# -*- coding: utf-8 -*-
# Generated by Django 1.11.5 on 2017-10-02 03:46
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('garderie', '0003_auto_20171002_0212'),
    ]

    operations = [
        migrations.AddField(
            model_name='children',
            name='Parents',
            field=models.ManyToManyField(related_name='childrens', to='garderie.Parent'),
        ),
        migrations.AlterField(
            model_name='parent',
            name='Childrens',
            field=models.ManyToManyField(through='garderie.Parent_Children', to='garderie.Children'),
        ),
    ]
